---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-helm-module
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
{{- include "labels" . | indent 2 }}